### ISSUE TITLE
t.slice is not a function

### ISSUE THREAD

**Issue by abnerlee** [mhchem/MathJax-mhchem#20] opened 2021-07-23 09:27 UTC
Hi, we received an error `t.slice is not a function` in our sentry server. Sorry, I didn't find the TeX script to trigger this issue.

But I guess it happens in 
```
MhchemMethods.Machine = function(parser: TexParser, name: string, machine: string) {
  try {
    let arg = parser.GetArgument(name);
    let data = mhchemParser.go(arg, machine);
    // TODO: Harvest chemical information here from data, test looping through
    //       the array.
    let tex = texify.go(data);
    parser.string = tex + parser.string.substr(parser.i);
    parser.i = 0;
  } catch (err) {
    throw new TexError(err[0], err[1], err.slice(2));
  }
};
```

where `err` is not an `Array` in some cases (maybe `Error` thrown in some of the logic inside)

**Comment by mhchem** [comment] 2021-07-23 10:59
It's a pity you did not find the TeX code to trigger this issue. What version of MathJax are you using? Do you use an external version of mhchem or the integrated one?

**Comment by abnerlee** [comment] 2021-07-24 01:34
MathJax 3.2.0, I'm using the tex-svg-full.js built by MathJax.

From the code, if any unexpected `Error` throws in
```
let arg = parser.GetArgument(name);
let data = mhchemParser.go(arg, machine);
let tex = texify.go(data);
```

Then, err will be an `Error` type, which do not have the `.slice` function. Only expected ones (thrown by your code), it would be OK.

**Comment by mhchem** [comment] 2021-09-13 20:13
@abnerlee Were you able to find TeX input that triggers the issue?

**Comment by abnerlee** [comment] 2021-09-15 06:57
Sorry, No~ We found it in our sentry server, not from customers' report, so we don't know user's exact input.

**Comment by abeeonthemoon** [comment] 2021-10-26 03:53
Hi!

I had an issue that was similar to this. I am using a library called rehype-mathjax to render my mathjax. Currently rehype-mathjax uses the latest version of mathjax. The issue occurred when I typed \ce in the editor. 

Note: When I copy and paste the following equation: \ce{CO2 + C -> 2 CO}, it works perfectly fine. However when I am in the process of typing input, then by the time I type \ce that's when I get this error.

Please let me know if I can provide anything else to present this issue. Thank you.

**Comment by wb-joona** [comment] 2022-02-14 11:58
I was able to [reproduce this issue with MathJax 3.2.0](https://github.com/mathjax/MathJax/issues/2835). It's caused by a missing closing bracket in the input. Try rendering `\ce{H2O` for example ([demo](https://codesandbox.io/s/nice-dhawan-yu49p?file=/index.html))

The issue is that the caught error is not an array like the `catch` block in MathJax assumes, but e.g.

```js
{
  id: 'MissingCloseBrace',
  message: 'Missing close brace'
}
```

which does not have a `.slice()` method.

**Comment by mhchem** [comment] 2022-02-14 16:58
That demo was very helpful. I think the bug is with MhchemConfiguration. See my comments in the MathJax issue linked above.

**Comment by dpvc** [comment] 2022-02-19 00:16
I have made a PR to MathJax-src that addresses the issue.

**Closed as completed** 2022-08-10 06:17 UTC
Labels: waiting for upstream
