### ISSUE TITLE
JAWS screen reader reads out <mphantom>

### ISSUE THREAD

**Issue by amirah-learn** [mhchem/MathJax-mhchem#22] opened 2021-09-13 10:45 UTC
Hello,

**Describe the bug:**
- `<mphantom>` in chemical notation (`\ce{}`) are being read out as "X" in JAWS screen reader.
- For example: 
          -  SO<sub>4</sub> reads out "S O X sub 4"
- This issue does not occur on:
                https://developer.mozilla.org/en-US/docs/Web/MathML/Element/mphantom

**To Reproduce:**
1.  Go to 'katex.org' or 'https://mhchem.github.io/MathJax-mhchem/' in Chrome on Windows 10
2.  Enter `\ce{SO4}`
3.  Enable JAWS
4.  Output reads as "S O X sub 4"

**Expected behavior:**
Read out as "S O sub 4"

**Environment:**
- OS : Windows 10
- Browser : Chrome 93.0.4577.63
- JAWS version : 2021.2105.53

Thanks for your time.

**Comment by mhchem** [comment] 2021-09-13 20:11
Could you please describe clearer where "X" is read out and where it is not?

**Comment by amirah-learn** [comment] 2021-09-14 10:49
> Could you please describe clearer where "X" is read out and where it is not?

Thank you for your quick response. I have edited my comment. 

This happens only on `\ce{}` environments and _does_ occur on Katex.org and https://mhchem.github.io/MathJax-mhchem/. Thus _is_ reading out the `<mphantom>` as " x ".

On https://developer.mozilla.org/en-US/docs/Web/MathML/Element/mphantom JAWS reads as expected : " x plus z". Thus here it is _not_ reading out the `<mphantom>`.

I have also attached a video with examples.

https://user-images.githubusercontent.com/82656745/133274367-97f3fff1-5098-4731-9782-6be4804b9b9b.mp4

**Comment by mhchem** [comment] 2021-09-16 19:16
Thanks. I think the problem is not with mhchem, but let's dig a bit deeper.
Could you test the input `$y^2 + \vphantom{X} + \vphantom{X}^2$` at https://www.mathjax.org/#demo and `y^2 + \vphantom{X} + \vphantom{X}^2` at <https://katex.org/>? Does it read the X's?

**Comment by amirah-learn** [comment] 2021-09-20 08:45
Hi, 

In both instances the X is read out.

https://user-images.githubusercontent.com/82656745/133976430-5c19d711-f04b-4c1d-b19c-1feeddf97f68.mp4

**Comment by pkra** [comment] 2021-09-20 14:47
This is a bug in browsers and/or JAWS - not mhchem. 

phantom content is purely spacing information and child content should not be exposed to/by AT. For example, MathJax's Accessibility Extensions will render this correctly.

**Comment by mhchem** [comment] 2021-09-20 18:28
I was about to close this issue here and forward it to the MathJax developers, because this is something that happens with every phanom, not just with mhchem. But pkra gave the respective assessment. I close this issue and recommend reaching out to the JAWS team.

**Closed as completed by mhchem** 2021-09-20 18:28 UTC
